--- config/elasticsearch.yml.orig	2018-02-16 18:57:55 UTC
+++ config/elasticsearch.yml
@@ -31,10 +31,12 @@
 # Path to directory where to store the data (separate multiple locations by comma):
 #
 #path.data: /path/to/data
+path.data: /var/db/elasticsearch
 #
 # Path to log files:
 #
 #path.logs: /path/to/logs
+path.logs: /var/log/elasticsearch
 #
 # ----------------------------------- Memory -----------------------------------
 #
@@ -86,3 +88,13 @@
 # Require explicit names when deleting indices:
 #
 #action.destructive_requires_name: true
+#
+# ---------------------------DragonFly specific options-------------------------
+#
+# Java Native Interface code doesn't work on DragonFly
+#
+bootstrap.system_call_filter: false
+#
+# The default mmapfs storage engine is prone to memory leaks
+#
+index.store.type: niofs
