--- cargo-crates/ring-0.16.11/Cargo.toml.orig	2020-02-04 18:53:34 UTC
+++ cargo-crates/ring-0.16.11/Cargo.toml
@@ -65,7 +65,7 @@ default-features = false
 version = "0.3.25"
 features = ["Crypto", "Window"]
 default-features = false
-[target."cfg(any(target_os = \"android\", target_os = \"freebsd\", target_os = \"linux\", target_os = \"netbsd\", target_os = \"openbsd\", target_os = \"solaris\"))".dependencies.lazy_static]
+[target."cfg(any(target_os = \"android\", target_os = \"freebsd\", target_os = \"dragonfly\", target_os = \"linux\", target_os = \"netbsd\", target_os = \"openbsd\", target_os = \"solaris\"))".dependencies.lazy_static]
 version = "1.3"
 optional = true
 default-features = false
